# Generated by Django 5.2.6 on 2025-11-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('POB', models.CharField(max_length=200)),
                ('DOB', models.DateField(null=True)),
            ],
        ),
    ]
